ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

# Ansible Playbook for Getting Package Data

This contains automation playbooks for getting various forms of package data. It should have some examples for outputs to STDOUT and files.

.Getting a YAML Formatted File Listing Locally in a File
[source,yaml]
----
  - name: Capture list of packages to be updated in a file
    local_action:
      module: copy
      content: "{{ yum_output.results | map(attribute='name') | list | sort | to_nice_yaml}}"
      dest: packages.txt
----

.Getting a CSV Formatted File Listing Locally in a File
[source,yaml]
----
  - name: Capture list of packages to be updated in a file
    local_action:
      module: copy
      content: "{{ yum_output.results | map(attribute='name') | list | sort }}"
      dest: packages.txt
----

.Sorting and Formatting Output
[NOTE]
====
The items above process the values mapping the name output into a list. It further *sorts* the list for easier comparisons.
====


.Privileges and Security
[IMPORTANT]
====
The *RPM_Reports.yml* playbook also gives an example of _Least Privileges_ in that only the task in the playbook requiring elevated privileges causes the task to be run as root. All other tasks are run as the regular standard user without additional system privileges.
====
